Update 2042005.js
lightryuzaki/ProjectNano4 pull request #35
Opened 2019-04-12 03:13 UTC by Evol93

Change text to English and add Map in use check

2019-04-12 17:38 UTC, minimucho1 requested changes

2019-04-12 17:38 UTC, minimucho1 commented on scripts/npc/2042005.js
> +                    if (!cm.sendCPQMapLists2()) {
What is this condition checking for? `sendCPQMapLists2` always returns `void`

2019-04-12 17:47 UTC, minimucho1 commented on scripts/npc/2042005.js
> +                    if (!cm.sendCPQMapLists2()) {
There is also language referenced in `NPCConversationManager.java` that uses `LanguageConstants.java` to write the final message. We need to ensure that the final message is also using the correct localization.

2019-04-13 05:45 UTC, minimucho1 submitted a review, later dismissed
Looks good.

2019-04-13 05:46 UTC, minimucho1 commented
The only thing left is to amend these commits with the proper issue number before we merge.

2019-04-14 00:03 UTC, Evol93 commented
That should be it.

2019-04-14 05:46 UTC, minimucho1 commented
This is not following the commit message format. I can't merge this change in.

2019-04-14 05:47 UTC, minimucho1 commented
This PR has 29 commits that have multiple duplicates. We need to squash these commits and properly rebase them before merging this change in.

2019-04-14 05:48 UTC, minimucho1 requested changes
Please review my comments

2019-04-14 16:21 UTC, Evol93 commented
Ugh...how or what am i suppose to do. I dont use github.

2019-04-14 19:55 UTC, merged